.env, .env.example, .gitattributes, .gitignore, README.md, Web-Ods/Dockerfile, Web-Ods/appsettings.template.json, Web-Ods/run.sh, Web-Sandbox-Admin/Dockerfile, Web-Sandbox-Admin/appsettings.template.json, Web-Sandbox-Admin/run.sh, Web-SwaggerUI/Dockerfile, Web-SwaggerUI/appsettings.template.json, Web-SwaggerUI/run.sh, docker-compose-prod.yml, docker-compose-sandbox-env.yml
created .env file, updated .env into gitignore and updated env into docker-compose-prod.yml, docker-compose-sandbox-env.yml files, README.md
=> [ODS-4640] Use Environment File for configuration in docker

.env.example, Web-Gateway/nginx.conf, Web-Ods-AdminApp/Dockerfile, Web-Ods-AdminApp/README.md, Web-Ods-AdminApp/appsettings.template.json, Web-Ods-AdminApp/log4net.config, Web-Ods-AdminApp/run.sh, compose-shared-instance-env-build.yml
@jamessmckay @vimayya @stephenfuqua 
Changes:
1. Added admin app specific docker, appsettings, run.sh and log4net config file.
2. Updated compose-shared-instance-env-build.yml file to include admin app. compose-shared-instance-env.yml file will be updated once the docker image is available on docker hub.
3. Updated nginx config to include admin app server entry
4. Read-me file will be updated with image link details once the docker image is available on docker hub.
Thanks
=> [AA-1185] Add AdminApp docker setup files

Web-Ods-AdminApp/appsettings.template.json
Set DbSetupEnabled to false to disable the Setup tab under Settings section.
=> [AA-1219] - Disable Setup tab by default

README.md
@vimayya @jamessmckay @stephenfuqua @plioi 
Please help review the changes.
Thanks
=> [AA-1242] Update technical documentation for Docker use with respect to Admin App - README.md file updates

DB-Admin/Dockerfile, Web-Ods-AdminApp/Dockerfile
@saa14 @jamessmckay @stephenfuqua @plioi @vimayya 
Updated Admin app web package and database package versions to 2.1.1 on docker files.
=> [AA-1246] Update Admin app web package and database package release versions on docker files

.env.example, Web-Gateway/nginx.conf, Web-Ods-AdminApp/Dockerfile, Web-Ods-AdminApp/appsettings.template.json, compose-shared-instance-env-build.yml, compose-shared-instance-env.yml
@jamessmckay @vimayya @plioi 
Admin App code changes for defining PathBase: https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/165
Admin App docker file temporarily referring to admin app pre-release package. This will be updated after admin app 2.2 release.
https://tracker.ed-fi.org/browse/AA-1287
Thanks
=> [AA-1264] Update Admin App Virtual Endpoints Docker

.env.example, README.md, Web-Ods-AdminApp/README.md, Web-Ods-AdminApp/appsettings.template.json, compose-shared-instance-env-build.yml, compose-shared-instance-env.yml
@stephenfuqua @jamessmckay @plioi 
Thanks
=> [AA-1291] Use environment variable for ProductionApiUrl in appsettings.template.json

DB-Admin/Dockerfile, Web-Ods-AdminApp/Dockerfile, Web-Ods-AdminApp/appsettings.template.json, Web-Ods-AdminApp/run.sh
@CSR2017 to review, mentioning @jamessmckay for awareness. 
- Updated the AdminApp nuget package versions to the latest pre-release versions. 
**(A second final PR will update the files to use the 2.2.0 versions)**
- Successfully completed regression testing 
- Removed deprecated appsettings: SystemManagedSqlServer, DbSetupEnabled and EncryptionProtocol. 
- Added GoogleAnalyticsMeasurementId appsetting.
=> [AA-1287] - Updated appsettings for AdminApp along with nuget package version updates

.env.example, DB-Admin/Alpine/pgsql/Dockerfile, Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
Updated the AdminApp nuget package versions to the latest release versions.
=> AA-1287-Update AdminApp package versions to the latest release versions

.env.example, Compose/mssql/compose-shared-instance-env-build.yml, Compose/mssql/compose-shared-instance-env.yml, Compose/pgsql/compose-shared-instance-env-build.yml, Compose/pgsql/compose-shared-instance-env.yml, Web-Gateway/Alpine/default.conf.template, Web-Ods-AdminApp/Alpine/mssql/README.md, Web-Ods-AdminApp/Alpine/mssql/run.sh, Web-Ods-AdminApp/Alpine/pgsql/README.md, Web-Ods-AdminApp/Alpine/pgsql/run.sh, generate-cert.sh
@stephenfuqua @vimayya 
Please help review and merge the changes. Thanks
1. Update nginx to allow just SSL port. 
2. Enable port 80 for ODS API for internal communication from Admin app container. 
3. Refactor API_INTERNAL and API_EXTERNAL urls formation on compose files.
=> [AA-1248] Reconfigure Admin App to Access the API via NGiNX

Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile, Web-Ods-Api/Alpine/pgsql/Dockerfile, Web-Sandbox-Admin/Alpine/pgsql/Dockerfile
- Updated postgresql-client package to version 13.5 from 13.4
=> [AA-1396] - Updated postgresql-client package to version 13.5 from 13.4

DB-Admin/Alpine/pgsql/Dockerfile
- Updated `ADMINAPP_DATABASE_VERSION` in `DB-Admin/Alpine/pgsql/Dockerfile` to pull in the latest dbup scripts
=> [AA-1400] - Update Admin App Database package version

Web-Ods-AdminApp/Alpine/mssql/appsettings.template.json, Web-Ods-AdminApp/Alpine/pgsql/appsettings.template.json
- Removed old values on appsetings.json file for mssql since those are no longer needed.
- Added values for product registration URL on mssql and postgres
- Changed order of values in the json file to have the same structure as Admin App for mssql and postgres.
=> [AA-1322] Modifying appsettings json file to match the latest admin app entries

Compose/pgsql/compose-sandbox-env-build.yml, Compose/pgsql/compose-sandbox-env.yml
=> [AA-1285] Add API_MODE on admin database section 

DB-Admin/Alpine/pgsql/Dockerfile, Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
- Updated Admin App web and database package versions to the latest release version 2.3.2
=> [AA-1404] - Updated Admin App packages to the latest release version 2.3.2

Compose-Generator/Alpine/templates/pgsql/template.mustache, Compose/pgsql/compose-district-specific-env-build.example.yml, Compose/pgsql/compose-shared-instance-env-build.yml, Compose/pgsql/compose-year-specific-env-build.example.yml
This affects when running on GitHub actions with an Ubuntu Image
=> Fixing references to DB-ODS folder since this fails on case sensitive OS

Web-Ods-Api/Alpine/mssql/Dockerfile, Web-Ods-Api/Alpine/pgsql/Dockerfile
Patch release for NHibernate case sensitivity issue (v5.3)
=> [ODS-5400] Patch release for NHibernate case sensitivity issue (v5.3)

DB-Admin/Alpine/pgsql/README.md, DB-ODS/Alpine/pgsql/README.md, DB-Sandbox/Alpine/pgsql/README.md, Web-Gateway-Sandbox/Alpine/README.md, Web-Gateway/Alpine/README.md, Web-Ods-AdminApp/Alpine/mssql/README.md, Web-Ods-AdminApp/Alpine/pgsql/README.md, Web-Ods-Api/Alpine/mssql/README.md, Web-Ods-Api/Alpine/pgsql/README.md, Web-Sandbox-Admin/Alpine/mssql/README.md, Web-Sandbox-Admin/Alpine/pgsql/README.md, Web-SwaggerUI/Alpine/README.md
Update Readme files to include new v2.1.2 links.
=> [ODS-5485] - Patch release for X-Forward header issue (v5.3)

.env.example
- Re-organize file so like elements are close to each other. 
- add comments describing each var and how it's used.
- comment out variables with sane defaults so new folks can just run with this without having to look up everything.
=> [ODS-5483] re-org example env vars file and add doc comments

Web-Ods-AdminApp/Alpine/mssql/run.sh, Web-Ods-AdminApp/Alpine/pgsql/run.sh
=> SSL cert error

Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/mssql/appsettings.template.json, Web-Ods-AdminApp/Alpine/mssql/run.sh, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/appsettings.template.json, Web-Ods-AdminApp/Alpine/pgsql/run.sh
@jasonh-edfi @lchavarriaga @jagudelo-gap 
Thanks
Note: Will be updating the AdminApp package version after AdminApp release.
=> [AA-1654] Remove product improvement implementations

DB-Admin/Alpine/pgsql/Dockerfile, Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile
=> Update Admin App package version on docker files

Web-Ods-AdminApp/Alpine/pgsql/Dockerfile, Web-Ods-Api/Alpine/mssql/Dockerfile, Web-Ods-Api/Alpine/pgsql/Dockerfile, Web-Sandbox-Admin/Alpine/pgsql/Dockerfile
> [pgsql-admin 6/6] RUN apk --no-cache add unzip=~6.0 dos2unix=~7.4 bash=~5.1 gettext=~0.21 postgresql-client=~13.7-r0 icu=~67.1 &&     wget -O /app/SandboxAdmin.zip https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi/nuget/packages/EdFi.Suite3.Ods.SandboxAdmin/versions/5.3.1285/content &&     unzip /app/SandboxAdmin.zip -d /app &&     rm -f /app/SandboxAdmin.zip &&     rm -f /app/appsettings.json &&     cp /app/log4net.txt /app/log4net.config &&     dos2unix /app/*.json &&     dos2unix /app/*.sh &&     dos2unix /app/log4net.config &&     chmod 700 /app/run.sh &&     rm -f /app/*.exe:
#0 0.630 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#0 1.651 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX. …
=> [ODS-5806] Ed-Fi ODS Docker v2.1.3 for EdFi.Suite3.Ods.WebApi package version 5.3.1483 updated v5.3-patch4

DB-Admin/Dockerfile, DB-ODS/Dockerfile, DB-Sandbox/Dockerfile, Web-Gateway-Sandbox/Dockerfile, Web-Gateway/Dockerfile, Web-Ods-AdminApp/Dockerfile, Web-Ods-Api/Dockerfile, Web-Sandbox-Admin/Dockerfile, Web-SwaggerUI/Dockerfile
Note :https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi/overview/5.1.1 published to Azure in Release Feed
=> [ODS-5806] Ed-Fi ODS Docker v1.1.1 for EdFi.Suite3.Ods.WebApi package version 5.1.1 updated v5.1-patch2

Compose-Generator/Alpine/Dockerfile, Compose-Generator/Alpine/templates/pgsql/MultiTenant/appsettings-template.mustache, Compose-Generator/Alpine/templates/pgsql/MultiTenant/bootstrap-template.mustache, Compose-Generator/Alpine/templates/pgsql/MultiTenant/compose-template.mustache, Compose-Generator/Alpine/templates/pgsql/MultiTenant/parameters.example.yml, Compose-Generator/Alpine/templates/pgsql/MultiTenant/run.sh, Compose/pgsql/MultiTenant/appsettings.dockertemplate.json, Compose/pgsql/MultiTenant/bootstrap.sh, Compose/pgsql/MultiTenant/compose-multi-tenant-env.yml, multi-tenant-env-up.ps1
To test compose generator run
`docker run --rm -v "<PATH TO Ed-Fi-ODS-Docker/Compose-Generator/Alpine/templates/pgsql/MultiTenant/parameters.example.yml>:/parameters -v <PATH TO Ed-Fi-ODS-Docker/Compose/pgsql/MultiTenant>:/output edfiodsdocker multiTenant.sh`
=> [ODS-6029] Compose Generator MultiTenant setup

.env.example, Compose-Generator/Alpine/templates/pgsql/SingleTenant-OdsContext/compose-template.mustache, Compose/pgsql/SingleTenant-OdsContext/compose.yml, Compose/pgsql/SingleTenant/compose-single-tenant-odscontext-env.yml, Web-Gateway/Alpine/Dockerfile, Web-Gateway/Alpine/README.md, Web-Gateway/Alpine/default.conf.template
=> [ADMINAPI-347] Update references from Admin App to Admin API in Docker Deployment

DB-Admin/Alpine/pgsql/Dockerfile, DB-ODS/Alpine/pgsql/Dockerfile, DB-Sandbox/Alpine/pgsql/Dockerfile, NOTICES.md, README.md, Web-Gateway-Sandbox/Alpine/Dockerfile, Web-Gateway/Alpine/Dockerfile, Web-Ods-AdminApp/Alpine/mssql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/Dockerfile, Web-Ods-AdminApp/Alpine/pgsql/run.sh, Web-Ods-Api/Alpine/mssql/Dockerfile, Web-Ods-Api/Alpine/pgsql/Dockerfile, Web-Ods-Api/Alpine/pgsql/run.sh, Web-Sandbox-Admin/Alpine/mssql/Dockerfile, Web-Sandbox-Admin/Alpine/pgsql/Dockerfile, Web-Sandbox-Admin/Alpine/pgsql/run.sh, Web-SwaggerUI/Alpine/Dockerfile
Note that this includes additional improvements from:
* ODS-6061
* ODS-6054
* ODS-5778
=> [ODS-6178] Updates for ODS/API v6.2
